steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-394721/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/sleepr-394721/reservations/production',
    ]

  # auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-394721/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/sleepr-394721/auth/production',
    ]

  # payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-394721/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/sleepr-394721/payments/production',
    ]

  # notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/sleepr-394721/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/sleepr-394721/notifications/production',
    ]