apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/sleepr-394721/reservations/production
          name: reservations
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-connection
                  key: connectionString

            - name: HTTP_PORT
              value: "3004"

            - name: AUTH_SERVICE_HOST
              value: auth-tcp

            - name: AUTH_SERVICE_PORT
              value: "3002"

            - name: PAYMENTS_SERVICE_HOST
              value: payments

            - name: PAYMENTS_SERVICE_PORT
              value: "3001"

          ports:
            - containerPort: 3004
